### ISSUE TITLE
seedlink: section 'seedlink' doesn't exist in file 'seedlink.cfg'

### ISSUE THREAD

**Issue by cajaraujo** [SeisComP/seedlink#10]
Hie guys,
i've some difficult to start the seedlink server after install seiscomp from pre-built binaries. Basically, when i try launch seedlink server from command line passing the '.cfg' file like argument, the following mesage appears: seedlink: section 'seedlink' doesn't exist in file '../etc/defaults/seedlink.cfg'. Also, I've to say that the '.cgf' file is based on provided from seiscomp project on github. What am I doing wrong?

The best regards, Cleir

**Comment by andres-h** [comment]
The standard procedure is calling `seiscomp update-config` and `seiscomp start seedlink`. In this case seiscomp.cfg is preprocessed and seiscomp/var/lib/seedlink/seedlink.ini is generated. seiscomp.cfg cannot be passed to seedlink directly.
