### ISSUE TITLE
chain plugin: lost connection when trying to rename station

### ISSUE THREAD

**Issue by filefolder** [SeisComP/seedlink#13]
Hi all

I am noticing that when trying to rename the `station` parameter on the seedlink/chain plugin to anything but the station name the digitiser is programmed as, the seedlink buffer won't fill. For example the site name is "TIE03" but I am attempting to name it to "TEST"

![Screenshot at 2024-02-02 14-54-38](https://github.com/SeisComP/seedlink/assets/22922540/c7a1d115-6140-4354-8017-6416b07bb534)

The log doesn't show anything wrong as far as I can tell

```
Fri Feb  2 14:46:22 2024 - chain0: [10.232.1XX.15:18000] network socket opened
Fri Feb  2 14:46:22 2024 - chain0: [10.232.1XX.15:18000] connected to: SEEDLINK v3.1 (Nanometrics on centaur-3 4.6.16)
Fri Feb  2 14:46:22 2024 - chain0: [10.232.1XX.15:18000] organization: SerialNumber: 10012
Fri Feb  2 14:46:22 2024 - chain0: [M8_TEST] requesting next available data
Fri Feb  2 14:46:22 2024 - chain0: [10.232.1XX.15:18000] 1 station(s) accepted
```

If I disable the `station` parameter OR set it to the correct name, the buffer fills and archives as expected. Occurs with both Nanometrics and Guralp equipment. Seiscomp 5.10 

Working for anyone else?

**Comment by gempa-jabe** [comment]
This is not a development question. Please use the forums for that. In order to push data as TEST, you need to setup the station TEST locally. The local station name is TEST and the renamed station (the source) is TIE03.

**Comment by filefolder** [comment]
Apologies, I misunderstood how the code works so thought it might be a bug. I do try to sort my bugs and usage questions but have been failing of late!
