### ISSUE TITLE
gdrt_plugin/udpclient.h - use boost io_context instead of deprecated io_service

### ISSUE THREAD

**Issue by gilcel** [SeisComP/seedlink#19]
When compiling with Boost v1.87 (on macOS), I get the following error:

`seedlink/plugins/gdrt_plugin/udpclient.h:42:16: error: no type named 'io_service' in namespace 'boost::asio'`

Suggestion:
Use `boost::asio::io_context` instead of `boost::asio::io_service` which is deprecated since v1.66

Discussion here:
https://github.com/boostorg/asio/issues/110

In `seedlink/plugins/gdrt_plugin/udpclient.h` change line 42 from:

`boost::asio::io_service _ioService;`

to:
`boost::asio::io_context _ioService;`

then it compiles fine.

**Comment by gempa-jabe** [comment]
I have changed it in master and will check if all supported distribution will still compile.

**Comment by gilcel** [comment]
As expected, compiles fine now! Can be closed.
Thanks
